// Generated by `customtale-protocol-tools`

#![allow(non_snake_case)]
#![cfg_attr(rustfmt, rustfmt::skip)]

use anyhow::Context as _;
use bytes::{Bytes, BytesMut};

use crate::packets::AnyPacket;

#[track_caller]
fn check_round_trip(id: u32, data: &'static [u8]) {
    if let Err(err) = check_round_trip_fallible(id, data) {
        panic!("{err:?}");
    }
}

#[track_caller]
fn check_round_trip_fallible(id: u32, data: &'static [u8]) -> anyhow::Result<()> {
    let Some(descriptor) = AnyPacket::descriptor_for(id) else {
        eprintln!("(skipping)");
        return Ok(());
    };

    let decoded = AnyPacket::decode(id, Bytes::from_static(data))
        .with_context(|| format!("failed to decode {}", descriptor.name))?;

    let mut target = BytesMut::new();
    decoded
        .encode(&mut target)
        .with_context(|| format!("failed to encode {}", descriptor.name))?;

    assert_eq!(&target[..], data, "failed to round-trip {}", descriptor.name);

    Ok(())
}

