// Generated by `customtale-protocol-tools`

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use std::fmt;

use bytes::{Bytes, BytesMut};
use uuid::Uuid;

use crate::serde::*;

bitflags::bitflags! {
    #[derive(Debug, Copy, Clone, Hash, Eq, PartialEq)]
    pub struct PacketCategory: u32 {
        const ASSET_EDITOR = 1 << 0;
        const ASSETS = 1 << 1;
        const AUTH = 1 << 2;
        const BUILDER_TOOLS = 1 << 3;
        const CAMERA = 1 << 4;
        const CONNECTION = 1 << 5;
        const ENTITIES = 1 << 6;
        const INTERACTION = 1 << 7;
        const INTERFACE = 1 << 8;
        const INVENTORY = 1 << 9;
        const MACHINIMA = 1 << 10;
        const PLAYER = 1 << 11;
        const SERVER_ACCESS = 1 << 12;
        const SETUP = 1 << 13;
        const WINDOW = 1 << 14;
        const WORLD = 1 << 15;
        const WORLD_MAP = 1 << 16;
    }
}

pub trait Packet: Into<AnyPacket> + fmt::Debug + Clone + Serde {
    const DESCRIPTOR: &'static PacketDescriptor;
}

#[derive(Debug, Clone)]
pub struct PacketDescriptor {
    pub name: &'static str,
    pub id: u32,
    pub is_compressed: bool,
    pub max_size: u32,
    pub category: PacketCategory,
}

impl fmt::Display for PacketDescriptor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({})", self.name, self.id)
    }
}

macro_rules! define_packets {
    (
        $($name:ident),*$(,)?
    ) => {
        #[derive(Debug, Clone)]
        pub enum AnyPacket {
            $($name (Box<$name>),)*
        }

        impl AnyPacket {
            pub const fn descriptor_for(id: u32) -> Option<&'static PacketDescriptor> {
                $(
                    if id == <self::$name as Packet>::DESCRIPTOR.id {
                        return Some(<self::$name as Packet>::DESCRIPTOR);
                    }
                )*

                None
            }

            pub fn decode(id: u32, contents: Bytes) -> anyhow::Result<Self> {
                $(
                    if id == <self::$name as Packet>::DESCRIPTOR.id {
                        return <self::$name as Serde>::decode(contents).map(Into::into);
                    }
                )*

                anyhow::bail!("unknown packet id {id:?}")
            }

            pub fn descriptor(&self) -> &'static PacketDescriptor {
                match self {
                    $(Self::$name(_) => <self::$name as Packet>::DESCRIPTOR,)*
                }
            }

            pub fn encode(&self, target: &mut BytesMut) -> anyhow::Result<()> {
                match self {
                    $(Self::$name(v) => Serde::encode(v, target),)*
                }
            }
        }

        $(
            impl From<self::$name> for AnyPacket {
                fn from(packet: self::$name) -> Self {
                    AnyPacket::$name(Box::new(packet))
                }
            }

            impl From<Box<self::$name>> for AnyPacket {
                fn from(packet: Box<self::$name>) -> Self {
                    AnyPacket::$name(packet)
                }
            }
        )*
    };
}
